import OpenAI from "openai";
export type Person={firstName:string|null;lastName:string|null;email:string|null;phone:string|null;dob:string|null;street:string|null;city:string|null;state:string|null;zip:string|null;ownership:number|null;title:string|null};
export type BrokerPrefill={kyc:{fundingAmount:number|null;purposeOfFunds:string|null;lookingFor:string|null;businessLocation:"Canada"|"United States"|null;industry:string|null;yearsInBusiness:number|null;annualRevenue:number|null;monthlyRevenue:number|null;accountsReceivable:number|null;fixedAssets:number|null};business:{legalName:string|null;businessName:string|null;address:string|null;city:string|null;state:string|null;zip:string|null;phone:string|null;website:string|null;startDate:string|null;businessStructure:string|null;employees:number|null;craBusinessNumber:string|null;naicsCode:string|null};applicant:Person;partner:Person|null;notFound:string[]};
const KEYS:(keyof Person)[]=["firstName","lastName","email","phone","dob","street","city","state","zip","ownership","title"];
const str=(v:unknown)=>{if(v==null)return null;const t=String(v).trim();return t&&!/^(n\/?a|none|null|unknown|-+)$/i.test(t)?t:null};
const num=(v:unknown)=>{if(typeof v==="number"&&Number.isFinite(v))return v;const t=str(v);if(!t)return null;const n=Number(t.replace(/[^0-9.\-]/g,""));return Number.isFinite(n)&&/\d/.test(t)?n:null};
const date=(v:unknown)=>{const t=str(v);return t&&/^\d{4}-\d{2}-\d{2}$/.test(t)?t:null};
export function toE164(v:unknown){const d=String(v??"").replace(/\D/g,"");return d.length===10?`+1${d}`:d.length===11&&d.startsWith("1")?`+${d}`:null}
function person(o:any):Person{const p=o&&typeof o==="object"?o:{};return{firstName:str(p.firstName),lastName:str(p.lastName),email:str(p.email)?.toLowerCase()??null,phone:toE164(p.phone)??str(p.phone),dob:date(p.dob),street:str(p.street),city:str(p.city),state:str(p.state),zip:str(p.zip),ownership:num(p.ownership),title:str(p.title)}}
export function normalizePrefill(raw:any):BrokerPrefill{const k=raw?.kyc??{},b=raw?.business??{},pp=raw?.partner&&typeof raw.partner==="object"?person(raw.partner):null;const loc=String(k.businessLocation??"").toLowerCase();const out:BrokerPrefill={kyc:{fundingAmount:num(k.fundingAmount),purposeOfFunds:str(k.purposeOfFunds),lookingFor:str(k.lookingFor),businessLocation:/canada|^ca$/.test(loc)?"Canada":/united states|usa|^us$|[eé]tats[- ]unis/.test(loc)?"United States":null,industry:str(k.industry),yearsInBusiness:num(k.yearsInBusiness),annualRevenue:num(k.annualRevenue),monthlyRevenue:num(k.monthlyRevenue),accountsReceivable:num(k.accountsReceivable),fixedAssets:num(k.fixedAssets)},business:{legalName:str(b.legalName),businessName:str(b.businessName)??str(b.legalName),address:str(b.address),city:str(b.city),state:str(b.state),zip:str(b.zip),phone:toE164(b.phone)??str(b.phone),website:str(b.website),startDate:date(b.startDate),businessStructure:str(b.businessStructure),employees:num(b.employees),craBusinessNumber:str(b.craBusinessNumber),naicsCode:str(b.naicsCode)},applicant:person(raw?.applicant),partner:pp&&(pp.firstName||pp.lastName)?pp:null,notFound:[]};if(out.kyc.annualRevenue==null&&out.kyc.monthlyRevenue!=null)out.kyc.annualRevenue=Math.round(out.kyc.monthlyRevenue*12);if(out.kyc.monthlyRevenue==null&&out.kyc.annualRevenue!=null)out.kyc.monthlyRevenue=Math.round(out.kyc.annualRevenue/12);for(const [key,v] of Object.entries(out.kyc))if(v==null)out.notFound.push(`kyc.${key}`);for(const [key,v] of Object.entries(out.business))if(v==null)out.notFound.push(`business.${key}`);for(const key of KEYS)if(out.applicant[key]==null)out.notFound.push(`applicant.${key}`);return out}
const PROMPT=`Extract ONLY written fields from this English or French commercial financing application. Never guess. Return JSON containing kyc, business, applicant, and partner; use null when absent. Amounts are plain dollar numbers, dates YYYY-MM-DD, and applicant is the principal owner, not the broker.\n`;
export async function extractPrefillFromText(text:string){if(!process.env.OPENAI_API_KEY)throw new Error("OPENAI_API_KEY is not set");const openai=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const r=await openai.chat.completions.create({model:process.env.BROKER_IMPORT_LLM_MODEL||process.env.BANKING_LLM_MODEL||"gpt-5.4-mini",response_format:{type:"json_object"},messages:[{role:"user",content:PROMPT+text.slice(0,60000)}]});let p:unknown={};try{p=JSON.parse(r.choices?.[0]?.message?.content??"{}")}catch{}return normalizePrefill(p)}
export async function documentText(data:Buffer,mime:string){if(mime==="application/pdf"){try{const {default:pdfParse}=await import("pdf-parse");const p=await (pdfParse as (b:Buffer)=>Promise<{text?:string}>)(data),t=String(p.text??"");if(t.replace(/\s/g,"").length>=200)return t}catch{}}if(mime==="application/pdf"||mime.startsWith("image/")){const {analyzeWithDocIntel}=await import("../../modules/ocr/azureDocIntelProvider.js");const r=await analyzeWithDocIntel(data,"prebuilt-read");if(typeof r?.content==="string")return r.content;return ((r?.pages??[]) as any[]).flatMap(p=>(p?.lines??[]).map((l:any)=>String(l?.content??""))).join("\n")}return mime.startsWith("text/")?data.toString("utf8"):""}
