// BF_SERVER_PRODUCT_QUESTIONS_v288
import { Router } from "express";
import jwt from "jsonwebtoken";
import { safeHandler } from "../../middleware/safeHandler.js";
import { dbQuery } from "../../db.js";
import { loadGaps, saveAnswers } from "../../services/productQuestions/service.js";
const router = Router();
const query = (sql: string, params: unknown[]) => dbQuery(sql, params as any[]) as any;
async function clientOwns(req: any, applicationId: string): Promise<boolean> { const auth = String(req.headers?.authorization ?? ""); const secret = process.env.JWT_SECRET; if (!auth.startsWith("Bearer ") || !secret) return false; let phone10 = ""; try { const decoded = jwt.verify(auth.slice(7), secret) as Record<string, unknown>; phone10 = String(decoded.phone ?? "").replace(/[^0-9]/g, "").slice(-10); } catch { return false; } if (phone10.length !== 10) return false; const r = await dbQuery(`SELECT 1 FROM applications a LEFT JOIN application_contacts ac ON ac.application_id::text = a.id::text LEFT JOIN contacts c ON c.id = ac.contact_id OR c.id = a.contact_id WHERE a.id::text = ($1)::text AND right(regexp_replace(coalesce(c.phone, ''), '[^0-9]', '', 'g'), 10) = $2 LIMIT 1`, [applicationId, phone10]); return (r.rowCount ?? 0) > 0; }
function publicGaps(g: any) { return { category: g.category, set: g.set, setLabel: g.setLabel, submittedAt: g.submittedAt, missing: g.missing, questions: g.questions.map((q: any) => ({ id: q.id, key: q.key, label: q.label, type: q.type, section: q.section, required: q.required, options: q.options ?? null, showIf: q.showIf ?? null, ownerIndex: q.ownerIndex, ownerName: q.ownerName, value: q.value })) }; }
router.get("/applications/:id/product-questions", safeHandler(async (req: any, res: any) => { const id = String(req.params.id); if (!(await clientOwns(req, id))) return res.status(403).json({ error: "forbidden" }); const gaps = await loadGaps(query, id); if (!gaps) return res.status(404).json({ error: "not_found" }); return res.json(publicGaps(gaps)); }));
router.post("/applications/:id/product-questions", safeHandler(async (req: any, res: any) => { const id = String(req.params.id); if (!(await clientOwns(req, id))) return res.status(403).json({ error: "forbidden" }); const answers = req.body?.answers && typeof req.body.answers === "object" ? req.body.answers : {}; const submit = req.body?.submit === true; const result = await saveAnswers(query, id, answers, { submit: false, by: "client" }); if (!result) return res.status(404).json({ error: "not_found" }); if (submit) { if (result.gaps.missing.length) return res.status(422).json({ error: "questions_incomplete", ...publicGaps(result.gaps) }); const done = await saveAnswers(query, id, {}, { submit: true, by: "client" }); void import("../../services/productQuestions/sendGate.js").then((m) => m.notifyStaffQuestionsAnswered(query, id)); /* BF_SERVER_PRODUCT_SWITCH_RESIGN_v293 */ return res.json({ ok: true, rejected: result.rejected, ...publicGaps(done!.gaps) }); } return res.json({ ok: true, rejected: result.rejected, ...publicGaps(result.gaps) }); }));
export default router;
