// BF_SERVER_MEETING_NOTIFY_v741
import { describe, it, expect, vi } from "vitest";
import { notifyMeeting, cancelMeetingNotices, meetingSms, type MeetingNotifyDeps } from "../services/meetingNotify.js";
const room = { id: "r1", code: "926048", slug: "abc123", title: "Test Meeting", host_user_id: "u1", application_id: null, contact_id: null, starts_at: "2026-10-05T20:30:00Z", duration_min: 30, status: "scheduled" };
function deps(opts: { people?: any[]; host?: any; eventId?: string | null; graphOk?: boolean; graphReady?: boolean; emailOk?: boolean } = {}) {
  const sql: Array<[string, unknown[]]> = [];
  const graph = vi.fn(async (_p: string, _m: string, _b?: unknown) => ({ ok: opts.graphOk ?? true, status: opts.graphOk === false ? 403 : 201, json: { id: "EV1" }, text: opts.graphOk === false ? "ErrorAccessDenied" : "" }));
  const sms = vi.fn(async (_to: string, _t: string) => ({ ok: true }));
  const email = vi.fn(async (_to: string, _s: string, _h: string) => ({ ok: opts.emailOk ?? true }));
  const d: MeetingNotifyDeps = { graphReady: () => opts.graphReady ?? true, graph, sms, email, query: vi.fn(async (text: string, params: unknown[]) => { sql.push([text, params]); if (text.includes("FROM users")) return { rows: [opts.host ?? { name: "Todd W", email: "todd@boreal.financial", phone: "403-555-0111" }] }; if (text.includes("FROM meeting_participants")) return { rows: opts.people ?? [] }; if (text.includes("SELECT graph_event_id")) return { rows: [{ graph_event_id: opts.eventId ?? null, host_email: opts.eventId ? "todd@boreal.financial" : null }] }; return { rows: [] }; }) };
  return { d, sql, graph, sms, email };
}
const pat = { id: "p1", name: "Pat Client", email: "pat@example.com", phone: "+1 587 555 0122", invited_at: null, texted_at: null };
describe("conference room notices", () => {
  it("a room with nobody added still goes in the host's Outlook calendar and texts the host", async () => { const { d, graph, sms } = deps(); const out = await notifyMeeting(room, { isNew: true }, d); expect(out.calendar).toBe("created"); expect(graph.mock.calls[0][0]).toBe("/users/todd%40boreal.financial/events"); expect(graph.mock.calls[0][1]).toBe("POST"); expect(sms).toHaveBeenCalledTimes(1); expect(sms.mock.calls[0][0]).toBe("+14035550111"); expect(out.texted).toBe(1); });
  it("invites participants through Outlook and texts them with the code", async () => { const { d, graph, sms, sql } = deps({ people: [pat] }); const out = await notifyMeeting(room, { isNew: true }, d); const body: any = graph.mock.calls[0][2]; expect(body.attendees).toEqual([{ emailAddress: { address: "pat@example.com", name: "Pat Client" }, type: "required" }]); expect(out.emailed).toBe(1); expect(sms.mock.calls.map((c) => c[0])).toEqual(["+15875550122", "+14035550111"]); expect(sms.mock.calls[0][1]).toContain("code 926048"); expect(sql.some(([t]) => t.startsWith("UPDATE meeting_participants SET texted_at"))).toBe(true); expect(sql.some(([t]) => t.startsWith("UPDATE meeting_rooms SET graph_event_id"))).toBe(true); });
  it("adding people later updates the same Outlook event and only texts the new person", async () => { const { d, graph, sms } = deps({ people: [{ ...pat, invited_at: "x", texted_at: "x" }, { id: "p2", name: "Lee", email: "lee@example.com", phone: "4035550133", invited_at: null, texted_at: null }], eventId: "EV1" }); const out = await notifyMeeting(room, { isNew: false }, d); expect(out.calendar).toBe("updated"); expect(graph.mock.calls[0][1]).toBe("PATCH"); expect(sms.mock.calls.map((c) => c[0])).toEqual(["+14035550133"]); });
  it("when Outlook refuses, says so and emails the invite instead, host included", async () => { const { d, email } = deps({ people: [pat], graphOk: false }); const out = await notifyMeeting(room, { isNew: true }, d); expect(out.calendar).toBe("failed"); expect(out.errors.join(" ")).toContain("ErrorAccessDenied"); expect(email.mock.calls.map((c) => c[0])).toEqual(["pat@example.com", "todd@boreal.financial"]); });
  it("reports a host with no mobile instead of staying quiet", async () => { const { d } = deps({ host: { name: "Todd", email: "todd@boreal.financial", phone: null } }); const out = await notifyMeeting(room, { isNew: true }, d); expect(out.errors.join(" ")).toContain("no mobile number on your staff profile"); });
  it("cancelling cancels the Outlook event and texts people who were told", async () => { const { d, graph, sms } = deps({ people: [{ ...pat, texted_at: "x" }], eventId: "EV1" }); const out = await cancelMeetingNotices(room, d); expect(graph.mock.calls[0][0]).toBe("/users/todd%40boreal.financial/events/EV1/cancel"); expect(out.calendar).toBe("cancelled"); expect(sms.mock.calls[0][1]).toContain("has been cancelled"); });
  it("the text carries the code and one-tap dial", () => { expect(meetingSms(room)).toContain("+18666318939,,3,,,926048#"); });
});
