// BF_SERVER_PRODUCT_QUESTIONS_v288
import { QUESTION_SETS, questionSetFor, type Question, type QuestionSetId } from "./registry.js";
type Md = Record<string, any>;
const obj = (v: unknown): Md => v && typeof v === "object" && !Array.isArray(v) ? v as Md : {};
export function normalizeAnswer(q: Question, v: unknown): string {
  if (v == null) return "";
  if (q.type === "yesno") { if (v === true || /^(y|yes|true)$/i.test(String(v).trim())) return "Yes"; if (v === false || /^(n|no|false)$/i.test(String(v).trim())) return "No"; return ""; }
  return String(v).trim();
}
export type Owner = { index: number; name: string };
export function ownersOf(md: Md): Owner[] { const a = obj(md.applicant); const owners = [{ index: 0, name: [a.firstName, a.lastName].filter(Boolean).join(" ") || "Applicant" }]; const p = obj(a.partner); if (p.firstName || p.lastName) owners.push({ index: 1, name: [p.firstName, p.lastName].filter(Boolean).join(" ") }); return owners; }
function scopeObject(md: Md, q: Question, i: number): Md { if (q.scope === "business") return obj(md.business); if (q.scope === "kyc") return obj(md.kyc); const a = obj(md.applicant); return i === 0 ? a : obj(a.partner); }
function currentValue(md: Md, q: Question, i: number) { return normalizeAnswer(q, scopeObject(md, q, i)[q.key]); }
export type AnsweredQuestion = Question & { id: string; ownerIndex: number | null; ownerName: string | null; value: string; applies: boolean };
export function questionsForApplication(md: Md, setId: QuestionSetId): AnsweredQuestion[] { const set = QUESTION_SETS[setId]; const out: AnsweredQuestion[] = []; for (const q of set.questions) for (const t of q.scope === "owner" ? ownersOf(md) : [{ index: -1, name: "" }]) { const oi = q.scope === "owner" ? t.index : null; const value = currentValue(md, q, oi ?? 0); const gate = q.showIf ? currentValue(md, { ...q, key: q.showIf.key, type: set.questions.find(x => x.key === q.showIf!.key)?.type ?? "text" }, oi ?? 0) : null; out.push({ ...q, id: oi === null ? `${q.scope}.${q.key}` : `owner.${oi}.${q.key}`, ownerIndex: oi, ownerName: oi === null ? null : t.name, value, applies: !q.showIf || gate === q.showIf.equals }); } return out; }
export function missingQuestions(qs: AnsweredQuestion[]) { return qs.filter(q => q.required && q.applies && q.value === ""); }
export type Gaps = { category: string | null; set: QuestionSetId | null; setLabel: string | null; questions: AnsweredQuestion[]; missing: string[]; submittedAt: string | null };
export function computeGaps(app: { product_category: string | null; metadata: unknown }, accordMatched: boolean): Gaps { const md = obj(app.metadata); const set = questionSetFor(app.product_category, accordMatched); if (!set) return { category: app.product_category, set: null, setLabel: null, questions: [], missing: [], submittedAt: null }; const questions = questionsForApplication(md, set); const progress = obj(obj(md.product_questions)[set]); return { category: app.product_category, set, setLabel: QUESTION_SETS[set].label, questions, missing: missingQuestions(questions).map(q => q.id), submittedAt: typeof progress.submitted_at === "string" ? progress.submitted_at : null }; }
export function applyAnswers(metadata: unknown, setId: QuestionSetId, answers: Record<string, unknown>) { const md: Md = JSON.parse(JSON.stringify(obj(metadata))); const allowed = new Map(QUESTION_SETS[setId].questions.map(q => [q.key, q])); const owners = ownersOf(md).map(o => o.index); const applied: string[] = [], rejected: string[] = []; for (const [id, raw] of Object.entries(answers ?? {})) { const p = id.split("."); let q: Question | undefined; let oi = 0; if (p.length === 2 && (p[0] === "business" || p[0] === "kyc")) { q = allowed.get(p[1]); if (q?.scope !== p[0]) q = undefined; } else if (p.length === 3 && p[0] === "owner") { oi = Number(p[1]); q = allowed.get(p[2]); if (q && (q.scope !== "owner" || !owners.includes(oi))) q = undefined; } if (!q) { rejected.push(id); continue; } const value = normalizeAnswer(q, typeof raw === "string" ? raw.slice(0, 500) : raw); if (q.options && value && !q.options.includes(value)) { rejected.push(id); continue; } if (q.scope === "business") md.business = { ...obj(md.business), [q.key]: value }; else if (q.scope === "kyc") md.kyc = { ...obj(md.kyc), [q.key]: value }; else if (oi === 0) md.applicant = { ...obj(md.applicant), [q.key]: value }; else md.applicant = { ...obj(md.applicant), partner: { ...obj(obj(md.applicant).partner), [q.key]: value } }; if (q.key === "mailingSameAsOperating") md.business.mailingSameAsOperating = value === "Yes"; applied.push(id); } return { metadata: md, applied, rejected }; }
