// v134-triage
// Runs the suite, groups every failure by normalized error signature, and
// writes a committed markdown report. Signatures collapse N failures into the
// handful of real causes behind them.
import fs from 'node:fs';
import { spawnSync } from 'node:child_process';

const RESULTS = '/tmp/v134-results.json';
const OUT = 'CI_TRIAGE.md';

spawnSync('npx', ['vitest', 'run', '--reporter=json', '--outputFile=' + RESULTS], {
  stdio: 'inherit',
  shell: false,
});

let raw;
try {
  raw = JSON.parse(fs.readFileSync(RESULTS, 'utf8'));
} catch (err) {
  console.error('V134 FAIL: could not read vitest output: ' + err.message);
  process.exit(1);
}

function normalize(msg) {
  let s = String(msg || '').split('\n')[0].trim();
  s = s.replace(/\/[\w./-]+\.(ts|tsx|js)/g, 'FILE');
  s = s.replace(/\b\d+\b/g, 'N');
  s = s.replace(/["'`][^"'`]{0,60}["'`]/g, 'STR');
  s = s.replace(/\s+/g, ' ');
  return s.slice(0, 150);
}

const failures = [];
for (const suite of raw.testResults || []) {
  const file = String(suite.name || '').replace(process.cwd() + '/', '');
  for (const a of suite.assertionResults || []) {
    if (a.status !== 'failed') continue;
    const full = (a.failureMessages || [])[0] || '';
    failures.push({
      file,
      name: a.fullName || a.title || '',
      sig: normalize(full),
      first: String(full).split('\n').slice(0, 4).join('\n'),
    });
  }
}

const groups = new Map();
for (const f of failures) {
  if (!groups.has(f.sig)) groups.set(f.sig, []);
  groups.get(f.sig).push(f);
}
const ordered = [...groups.entries()].sort((a, b) => b[1].length - a[1].length);

const byFile = new Map();
for (const f of failures) byFile.set(f.file, (byFile.get(f.file) || 0) + 1);

const lines = [];
lines.push('# CI triage report');
lines.push('');
lines.push('Generated by scripts/triage.mjs (v134). Regenerate with `node scripts/triage.mjs`.');
lines.push('');
lines.push('- Failing assertions: ' + failures.length);
lines.push('- Failing files: ' + byFile.size);
lines.push('- Distinct signatures: ' + ordered.length);
lines.push('');
lines.push('## Signatures, most common first');
lines.push('');
ordered.forEach(([sig, list], i) => {
  const files = [...new Set(list.map((f) => f.file))];
  lines.push('### ' + (i + 1) + '. ' + list.length + ' failure(s) across ' + files.length + ' file(s)');
  lines.push('');
  lines.push('```');
  lines.push(sig);
  lines.push('```');
  lines.push('');
  lines.push('Files:');
  files.slice(0, 12).forEach((f) => lines.push('- `' + f + '`'));
  lines.push('');
  lines.push('First occurrence:');
  lines.push('');
  lines.push('```');
  lines.push(list[0].file + ' > ' + list[0].name);
  lines.push(list[0].first);
  lines.push('```');
  lines.push('');
});

lines.push('## Failing files by count');
lines.push('');
[...byFile.entries()]
  .sort((a, b) => b[1] - a[1])
  .forEach(([file, n]) => lines.push('- ' + String(n).padStart(3) + '  `' + file + '`'));
lines.push('');

fs.writeFileSync(OUT, lines.join('\n'), 'utf8');

console.log('');
console.log('V134 wrote ' + OUT);
console.log('V134 failures=' + failures.length + ' files=' + byFile.size + ' signatures=' + ordered.length);
console.log('');
console.log('V134 TOP SIGNATURES');
ordered.slice(0, 20).forEach(([sig, list], i) => {
  console.log('  [' + (i + 1) + '] x' + list.length + '  ' + sig);
});
